### ISSUE TITLE
-lpthread is sometimes needed

### ISSUE THREAD

**Issue by acnq** [ciaranm/multithreadedmaximumclique#1]
If you are using Red Hat Enterprise Linux, the `-lpthread` is necessary on the line 8 at `./Makefile`, otherwise the bug like below would be produced:
```
/usr/bin/ld: ../../gtest-1.7.0/libgtest.a(gtest-all.cc.o): undefined reference to symbol     'pthread_key_delete@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/tests/run_tests] Error 1
make[1]: *** [src/tests/CMakeFiles/run_tests.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ciaranm** [comment]
I would recommend switching to [the Glasgow Subgraph Solver](https://github.com/ciaranm/glasgow-subgraph-solver), which is actively maintained, rather than using this code.
